version: "3.7"

networks:
    fastapi:

services:
    fastapi-postgres:
        container_name: fastapi-postgres
        image: postgres
        restart: always
        networks:
            - fastapi
        environment:
            - POSTGRES_DB=fastapi-postgres
            - POSTGRES_USER=fastapi-postgres
            - POSTGRES_PASSWORD=fastapi-postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "54321:5432"

    fastapi-pgadmin:
        image: dpage/pgadmin4
        container_name: fastapi-pgadmin
        restart: always
        networks:
            - fastapi
        depends_on:
            - fastapi-postgres
        ports:
            - "5500:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@fastapi.com
            PGADMIN_DEFAULT_PASSWORD: fastapi
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    postgres-data:
    pgadmin-data:
